import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { CategorySearchBar } from "../components";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geist.className}>
        <main className="grid gap-8 min-h-screen p-8 content-start">
          <CategorySearchBar />
          {children}
        </main>
      </body>
    </html>
  );
}
